Repository anchore/syft, pull requests merged in 2020-10, with the labels that each got.

#204 Fix acceptance tests & add notification upon failures
  .github/workflows/acceptance-test.yaml
  test/acceptance/deb.sh
  test/acceptance/mac.sh
  test/acceptance/rpm.sh
Labels: bug, enhancement

#207 Add acceptance test to cover gem cataloger
  syft/cataloger/ruby/catalogers.go
  test/inline-compare/Makefile
  test/inline-compare/compare-all.sh
  test/inline-compare/compare.py
  test/integration/test-fixtures/image-pkg-coverage/ruby/specifications/bundler.gemspec
Labels: bug

#210 Run checks on PRs from forks
  .github/workflows/static-unit-integration.yaml
Labels: enhancement

#211 Update install script arguments for proper argument processing
  README.md
Labels: enhancement

#218 Allow for gemspec metadata fields to be optional
  syft/pkg/gem_metadata.go
Labels: bug

#240 Update doublestar to include fix for open dirs issue
  go.mod
  go.sum
Labels: bug

#235 Add java/npm to inline comparison
  test/inline-compare/.gitignore
  test/inline-compare/Makefile
  test/inline-compare/compare.py
  test/inline-compare/utils/__init__.py
  test/inline-compare/utils/format.py
  test/inline-compare/utils/image.py
  test/inline-compare/utils/inline.py
  test/inline-compare/utils/package.py
  test/inline-compare/utils/syft.py
Labels: 1 storypoint, enhancement

#245 Java cataloger miscellaneous fixes
  schema/json/schema.json
  syft/cataloger/java/archive_filename.go
  syft/cataloger/java/archive_parser.go
  syft/cataloger/java/archive_parser_test.go
  syft/cataloger/java/java_manifest.go
  syft/cataloger/java/java_manifest_test.go
  syft/pkg/java_metadata.go
Labels: bug
