Repository anchore/syft, pull requests merged in 2022-03, with the labels that each got.

#866 Add platform selection
  cmd/attest.go
  cmd/cmd.go
  cmd/packages.go
  cmd/power_user.go
  go.mod
  go.sum
  internal/config/application.go
  internal/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
  internal/formats/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
  internal/formats/syftjson/test-fixtures/snapshot/stereoscope-fixture-image-simple.golden
  syft/source/image_metadata.go
  syft/source/source.go
  syft/source/source_test.go
  test/cli/packages_cmd_test.go
  test/integration/catalog_packages_test.go
  test/integration/utils_test.go
Labels: enhancement

#868 Update yarn.lock parser to support latest (berry v3) format
  syft/pkg/cataloger/javascript/parse_yarn_lock.go
  syft/pkg/cataloger/javascript/parse_yarn_lock_test.go
  syft/pkg/cataloger/javascript/test-fixtures/yarn-berry/yarn.lock
Labels: enhancement

#880 RPM Epoch should be optional in the json schema
  internal/constants.go
  internal/formats/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
  internal/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
  internal/formats/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
  schema/json/schema-3.1.0.json
  syft/pkg/rpmdb_metadata.go
Labels: bug

#878 Upgrade vault api from v1.3.1 to v1.4.1
  go.mod
  go.sum
Labels: ecosystem:go

#745 Correct CycloneDX distro decoding, test relationships
  internal/formats/common/cyclonedxhelpers/decoder.go
  test/integration/encode_decode_cycle_test.go
Labels: bug

#827 Use go 1.18 buildinfo to catalog binaries
  .github/workflows/release.yaml
  .github/workflows/validations.yaml
  Makefile
  go.mod
  go.sum
  internal/constants.go
  internal/formats/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
  internal/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
  internal/formats/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
  schema/json/schema-3.1.1.json
  syft/pkg/cataloger/golang/binary_cataloger.go
  syft/pkg/cataloger/golang/binary_cataloger_test.go
  syft/pkg/cataloger/golang/exe.go
  syft/pkg/cataloger/golang/exe_test.go
  syft/pkg/cataloger/golang/internal/README.md
  syft/pkg/cataloger/golang/internal/xcoff/file.go
  syft/pkg/cataloger/golang/internal/xcoff/file_test.go
  syft/pkg/cataloger/golang/internal/xcoff/testdata/gcc-ppc32-aix-dwarf2-exec
  syft/pkg/cataloger/golang/internal/xcoff/testdata/gcc-ppc64-aix-dwarf2-exec
  syft/pkg/cataloger/golang/internal/xcoff/xcoff.go
  syft/pkg/cataloger/golang/parse_go_bin.go
  syft/pkg/cataloger/golang/parse_go_bin_test.go
  syft/pkg/cataloger/golang/scan_bin.go
  syft/pkg/cataloger/golang/test-fixtures/archs/.gitignore
  syft/pkg/cataloger/golang/test-fixtures/archs/Makefile
  syft/pkg/cataloger/golang/test-fixtures/archs/src/build.sh
  syft/pkg/cataloger/golang/test-fixtures/archs/src/go.mod
  syft/pkg/cataloger/golang/test-fixtures/archs/src/main.go
  syft/pkg/cataloger/golang/version.go
  syft/pkg/golang_bin_metadata.go
  syft/source/image_squash_resolver.go
  test/integration/regression_go_bin_scanner_arch_test.go
Labels: WIP

#905 Fix image cleanup when there is an error
  go.mod
  go.sum
Labels: bug

#906 Improve docker config support
  go.mod
  go.sum
Labels: enhancement

#911 bump strset version to fix 386 builds
  go.mod
  go.sum
Labels: bug

#928 Pull from DockerHub fails for public images when using SSO
  go.mod
  go.sum
Labels: bug
