Repository anchore/syft, pull requests merged in 2023-05, with the labels that each got.

#1773 Rename sbom.PackageCatalog to sbom.Packages
  cmd/syft/cli/eventloop/tasks.go
  syft/formats/common/cyclonedxhelpers/decoder.go
  syft/formats/common/cyclonedxhelpers/decoder_test.go
  syft/formats/common/cyclonedxhelpers/format.go
  syft/formats/common/spdxhelpers/to_format_model.go
  syft/formats/common/spdxhelpers/to_syft_model.go
  syft/formats/common/spdxhelpers/to_syft_model_test.go
  syft/formats/cyclonedxjson/decoder_test.go
  syft/formats/cyclonedxxml/decoder_test.go
  syft/formats/github/encoder.go
  syft/formats/github/encoder_test.go
  syft/formats/internal/testutils/utils.go
  syft/formats/spdxjson/decoder_test.go
  syft/formats/spdxtagvalue/encoder_test.go
  syft/formats/syftjson/decoder_test.go
  syft/formats/syftjson/encoder_test.go
  syft/formats/syftjson/to_format_model.go
  syft/formats/syftjson/to_syft_model.go
  syft/formats/syftjson/to_syft_model_test.go
  syft/formats/table/encoder.go
  syft/formats/text/encoder.go
  syft/pkg/cataloger/sbom/cataloger.go
  syft/sbom/sbom.go
  test/integration/all_layers_squashed_comparison_test.go
  test/integration/catalog_packages_test.go
  test/integration/mariner_distroless_test.go
  test/integration/node_packages_test.go
  test/integration/package_deduplication_test.go
  test/integration/regression_apk_scanner_buffer_size_test.go
  test/integration/regression_go_bin_scanner_arch_test.go
  test/integration/rust_audit_binary_test.go
  test/integration/sbom_cataloger_test.go
  test/integration/sqlite_rpmdb_test.go
  test/integration/utils_test.go
Labels: breaking change

#1819 fix: update cataloger to check for expressions before split
  syft/pkg/cataloger/apkdb/package.go
  syft/pkg/cataloger/apkdb/parse_apk_db_test.go
  syft/pkg/cataloger/apkdb/test-fixtures/multiple
Labels: bug

#1820 fix: update field plurality of 8.0.0 schema before release
  schema/json/schema-8.0.0.json
  syft/formats/common/cyclonedxhelpers/licenses.go
  syft/formats/common/cyclonedxhelpers/licenses_test.go
  syft/formats/syftjson/model/package.go
  syft/formats/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
  syft/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
  syft/formats/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
  syft/formats/syftjson/to_format_model.go
  syft/formats/syftjson/to_syft_model.go
  syft/pkg/cataloger/apkdb/parse_apk_db_test.go
  syft/pkg/cataloger/golang/licenses_test.go
  syft/pkg/cataloger/php/parse_installed_json_test.go
  syft/pkg/license.go
  syft/pkg/license_set.go
  syft/pkg/license_set_test.go
  syft/pkg/license_test.go
Labels: bug

#1801 Return both failures when failed to retrive an image with a scheme
  syft/source/source.go
Labels: bug

#1840 Fix directory resolver to consider CWD and root path input correctly
  syft/formats/common/spdxhelpers/to_format_model_test.go
  syft/internal/fileresolver/directory.go
  syft/internal/fileresolver/directory_indexer.go
  syft/internal/fileresolver/directory_indexer_test.go
  syft/internal/fileresolver/directory_test.go
  syft/internal/fileresolver/test-fixtures/req-resp/path/to/rel-inside.txt
  syft/internal/fileresolver/test-fixtures/req-resp/path/to/the/file.txt
  syft/internal/fileresolver/test-fixtures/req-resp/path/to/the/rel-outside.txt
  syft/internal/fileresolver/test-fixtures/req-resp/root-link
  syft/internal/fileresolver/test-fixtures/req-resp/somewhere/outside.txt
  syft/internal/fileresolver/unindexed_directory_test.go
  syft/pkg/cataloger/kernel/cataloger_test.go
  syft/pkg/license_set_test.go
Labels: bug

#1841 Add test to ensure package metadata is represented in the JSON schema
  .github/scripts/json-schema-drift-check.sh
  Makefile
  go.mod
  go.sum
  schema/json/generate/main.go
  schema/json/internal/generated.go
  schema/json/internal/metadata_types.go
  schema/json/main.go
  schema/json/main_test.go
Labels: json
