Repository anchore/syft, pull requests merged in 2023-07, with the labels that each got.

#1914 Add file source digest support
  .gitignore
  README.md
  cmd/syft/cli/attest/attest.go
  cmd/syft/cli/eventloop/tasks.go
  cmd/syft/cli/options/packages.go
  cmd/syft/cli/packages/packages.go
  cmd/syft/cli/poweruser/poweruser.go
  internal/config/application.go
  internal/config/source.go
  internal/file/digest.go
  internal/file/digest_test.go
  internal/file/test-fixtures/digest.txt
  syft/file/cataloger/filedigest/cataloger.go
  syft/file/cataloger/filedigest/cataloger_test.go
  syft/file/digest.go
  syft/formats/common/cyclonedxhelpers/external_references.go
  syft/pkg/cataloger/java/archive_parser.go
  syft/source/file_source.go
Labels: enhancement

#1907 fix: "or-later" suffix updated to consider deprecated "+" operator
  internal/spdxlicense/generate/generate_license_list_test.go
  internal/spdxlicense/generate/license.go
  internal/spdxlicense/generate/license_test.go
  internal/spdxlicense/license_list.go
  internal/spdxlicense/license_list_test.go
Labels: enhancement

#1932 Remove jotframe UI
  go.mod
  go.sum
  ui/deprecated.go
Labels: breaking-change

#1919 Add cataloger for Swift Package Manager.
  CONTRIBUTORS.md
  README.md
  internal/constants.go
  schema/json/schema-9.0.2.json
  syft/formats/common/spdxhelpers/source_info.go
  syft/formats/common/spdxhelpers/source_info_test.go
  syft/internal/packagemetadata/generated.go
  syft/pkg/cataloger/cataloger.go
  syft/pkg/cataloger/swift/cataloger.go
  syft/pkg/cataloger/swift/package.go
  syft/pkg/cataloger/swift/package_test.go
  syft/pkg/cataloger/swift/parse_package_resolved.go
  syft/pkg/cataloger/swift/parse_package_resolved_test.go
  syft/pkg/cataloger/swift/parse_podfile_lock.go
  syft/pkg/cataloger/swift/test-fixtures/Package.resolved
  syft/pkg/language.go
  syft/pkg/language_test.go
  syft/pkg/metadata.go
  syft/pkg/swiftpackagemanager_metadata.go
  syft/pkg/type.go
  syft/pkg/type_test.go
  test/integration/catalog_packages_cases_test.go
  test/integration/catalog_packages_test.go
  test/integration/test-fixtures/image-pkg-coverage/swift/Package.resolved
Labels: enhancement

#1968 Fix panic condition on docker pull failure
  cmd/syft/cli/packages/packages.go
  cmd/syft/internal/ui/ui.go
Labels: bug

#1982 Add metadata types to all CPE test fixtures
  syft/pkg/cataloger/common/cpe/generate_test.go
Labels: changelog-ignore
