Repository anchore/syft, pull requests merged in 2023-03, with the labels that each got.

#1601 feat: rust toolchain binary cataloger
  syft/pkg/cataloger/binary/cataloger_test.go
  syft/pkg/cataloger/binary/default_classifiers.go
  syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/rust-1.50.0/lib/rustlib/aarch64-apple-darwin/lib/libstd-f6f9eec1635e636a.dylib
  syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/rust-1.67.1/toolchains/stable-aarch64-apple-darwin/lib/libstd-16f2b65e77054c42.dylib
  syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/rust-1.67.1/toolchains/stable-x86_64-unknown-linux-musl/lib/libstd-86aefecbddda356d.so
Labels: enhancement

#1669 fix: remove author contributing to javascript CPEs
  syft/pkg/cataloger/common/cpe/generate_test.go
  syft/pkg/cataloger/common/cpe/javascript.go
Labels: bug

#1107 Add Basic Nix Cataloger
  schema/json/generate.go
  syft/file/classifier.go
  syft/pkg/cataloger/cataloger.go
  syft/pkg/cataloger/nixstore/cataloger.go
  syft/pkg/cataloger/nixstore/parse_nix.go
  syft/pkg/metadata.go
  syft/pkg/nix_store_metadata.go
  syft/pkg/type.go
Labels: changelog-ignore

#1703 feat: Add config option to allow user to select the default image source location
  README.md
  cmd/syft/cli/attest/attest.go
  cmd/syft/cli/packages/packages.go
  cmd/syft/cli/poweruser/poweruser.go
  internal/config/application.go
  syft/source/source.go
  syft/source/source_test.go
  test/integration/catalog_packages_test.go
  test/integration/utils_test.go
Labels: enhancement
