Repository anchore/syft, pull requests merged in 2023-02, with the labels that each got.

#1538 fix: update config struct to not decode password/key
  internal/config/attest.go
  test/cli/packages_cmd_test.go
Labels: security

#1536 feat: add postgresql classifier
  syft/pkg/cataloger/binary/cataloger_test.go
  syft/pkg/cataloger/binary/default_classifiers.go
  syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/postgresql-15.1/postgres
  syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/postgresql-15beta4/postgres
  syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/postgresql-9.5alpha1/postgres
  syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/postgresql-9.6.24/postgres
Labels: enhancement

#1567 fix: improve CPE and upstream generation logic for Alpine packages
  syft/pkg/cataloger/apkdb/package.go
  syft/pkg/cataloger/apkdb/package_test.go
  syft/pkg/cataloger/common/cpe/apk.go
  syft/pkg/cataloger/common/cpe/apk_test.go
  syft/pkg/cataloger/common/cpe/candidate_by_package_type.go
  syft/pkg/cataloger/common/cpe/generate.go
  syft/pkg/cataloger/common/cpe/generate_test.go
  syft/pkg/cataloger/common/cpe/python.go
Labels: bug

#1582 Fix cataloger selection to be more specific
  syft/pkg/cataloger/cataloger.go
  syft/pkg/cataloger/cataloger_test.go
Labels: bug

#1603 chore: fix cataloger_test
  syft/pkg/cataloger/binary/cataloger_test.go
Labels: changelog-ignore

#1614 fix: decoding null apk metadata pullDependencies
  syft/pkg/apk_metadata.go
  syft/pkg/apk_metadata_test.go
Labels: bug
