Repository anchore/syft, pull requests merged in 2023-09, with the labels that each got.

#2097 Expose cobra command in cli package
  cmd/syft/cli/cli.go
  cmd/syft/main.go
Labels: enhancement

#2126 Fix source-version typo in flag description
  cmd/syft/cli/options/catalog.go
Labels: documentation

#2160 Require ordering of relationships when comparing parser output
  .gitignore
  go.mod
  go.sum
  syft/pkg/cataloger/cpp/parse_conanlock_test.go
  syft/pkg/cataloger/internal/pkgtest/test_generic_parser.go
Labels: changelog-ignore

#2161 fix: prevent errors from clobbering terminal
  cmd/syft/cli/cli.go
  cmd/syft/internal/ui/select.go
  cmd/syft/internal/ui/select_windows.go
  cmd/syft/internal/ui/ui.go
  go.mod
Labels: bug

#2162 Correcting behavior based on Syft release v0.91.0 run
  .chronicle.yaml
  .github/actions/bootstrap/action.yaml
  .github/workflows/release.yaml
Labels: changelog-ignore, release
