Repository anchore/syft, pull requests merged in 2023-08, with the labels that each got.

#1980 feat: use originator logic to fill supplier
  syft/formats/common/spdxhelpers/to_format_model.go
  syft/formats/common/spdxhelpers/to_format_model_test.go
  syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXJSONDirectoryEncoder.golden
  syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXJSONImageEncoder.golden
  syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
  syft/formats/spdxjson/test-fixtures/snapshot/stereoscope-fixture-image-simple.golden
  syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXJSONSPDXIDs.golden
  syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
  syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueDirectoryEncoder.golden
  syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueImageEncoder.golden
  syft/formats/spdxtagvalue/test-fixtures/snapshot/stereoscope-fixture-image-simple.golden
Labels: enhancement

#2011 1948-filter-pkg-by-type
  README.md
  syft/lib.go
  syft/pkg/cataloger/alpm/cataloger.go
  syft/pkg/cataloger/apkdb/cataloger.go
  syft/pkg/cataloger/binary/cataloger.go
  syft/pkg/cataloger/binary/package.go
  syft/pkg/cataloger/deb/cataloger.go
  syft/pkg/cataloger/nix/cataloger.go
  syft/pkg/cataloger/nix/cataloger_test.go
  syft/pkg/cataloger/nix/package.go
  syft/pkg/cataloger/package_exclusions.go
  syft/pkg/cataloger/package_exclusions_test.go
  syft/pkg/cataloger/rpm/cataloger.go
Labels: changelog-ignore

#2032 feat: use java package names to determine known groupids
  syft/pkg/cataloger/common/cpe/java.go
  syft/pkg/cataloger/common/cpe/java_groupid_map.go
  syft/pkg/cataloger/common/cpe/java_test.go
  syft/pkg/cataloger/java/package_url.go
Labels: enhancement

#2042 New version notice only showing the version and no text
  cmd/syft/internal/ui/__snapshots__/post_ui_event_writer_test.snap
  cmd/syft/internal/ui/post_ui_event_writer.go
  cmd/syft/internal/ui/post_ui_event_writer_test.go
Labels: bug

#2021 Detect golang boring crypto and fipsonly modules
  go.mod
  go.sum
  internal/constants.go
  schema/json/schema-10.0.1.json
  syft/pkg/cataloger/golang/package.go
  syft/pkg/cataloger/golang/parse_go_binary.go
  syft/pkg/cataloger/golang/parse_go_binary_test.go
  syft/pkg/cataloger/golang/scan_binary.go
  syft/pkg/cataloger/golang/scan_binary_test.go
  syft/pkg/golang_metadata.go
Labels: enhancement

#2059 chore: Trace log pom property reflect usage
  syft/pkg/cataloger/java/parse_pom_xml.go
  syft/pkg/cataloger/java/parse_pom_xml_test.go
Labels: changelog-ignore

#2065 chore: update quill to the latest version
  .github/workflows/update-bootstrap-tools.yml
  Makefile
Labels: changelog-ignore

#2081 Fix quiet flag
  cmd/syft/cli/cli.go
  test/cli/packages_cmd_test.go
  test/cli/trait_assertions_test.go
Labels: bug

#2082 Tidy the go.mod and .gitignore
  .gitignore
  go.mod
Labels: changelog-ignore

#2075 fix: correct group IDs for commons-codec, okhttp, okio, and add integration tests for Java PURL generation
  syft/pkg/cataloger/common/cpe/java_groupid_map.go
  test/integration/java_purl_test.go
  test/integration/test-fixtures/image-test-java-purls/Dockerfile
Labels: bug
