Repository anchore/syft, pull requests merged in 2023-11, with the labels that each got.

#2286 Use case-insensitive matching for Go license files
  syft/pkg/cataloger/golang/licenses.go
  syft/pkg/cataloger/golang/licenses_test.go
  syft/pkg/cataloger/golang/test-fixtures/licenses/pkg/mod/github.com/someorg/strangelicense@v1.2.3/LiCeNsE.tXt
Labels: enhancement

#2300 SPDX file has duplicate sha256 tag in versionInfo
  syft/source/file_source.go
  syft/source/file_source_test.go
Labels: bug

#2287 Add accessPath on Location objects to syft-json output
  internal/constants.go
  schema/json/schema-12.0.1.json
  syft/file/location.go
  syft/format/syftjson/encoder_test.go
  syft/format/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
  syft/format/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
  syft/format/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
Labels: json-schema

#2324 fix: capture content written to stdout outside of report
  cmd/syft/cli/cli.go
  cmd/syft/internal/ui/__snapshots__/event_writer_test.snap
  cmd/syft/internal/ui/__snapshots__/post_ui_event_writer_test.snap
  cmd/syft/internal/ui/capture.go
  cmd/syft/internal/ui/capture_test.go
  cmd/syft/internal/ui/event_writer.go
  cmd/syft/internal/ui/event_writer_test.go
  cmd/syft/internal/ui/log_writer.go
  cmd/syft/internal/ui/log_writer_test.go
  cmd/syft/internal/ui/no_ui.go
  cmd/syft/internal/ui/stdout_logging_application.go
  cmd/syft/internal/ui/ui.go
  go.mod
Labels: bug

#2275 Add "pretty" json configuration and change default behavior to be space-efficient
  README.md
  cmd/syft/cli/options/format.go
  cmd/syft/cli/options/format_cyclonedx_json.go
  cmd/syft/cli/options/format_cyclonedx_json_test.go
  cmd/syft/cli/options/format_cyclonedx_xml.go
  cmd/syft/cli/options/format_cyclonedx_xml_test.go
  cmd/syft/cli/options/format_json.go
  cmd/syft/cli/options/format_spdx_json.go
  cmd/syft/cli/options/format_spdx_json_test.go
  cmd/syft/cli/options/format_syft_json.go
  cmd/syft/cli/options/format_syft_json_test.go
  cmd/syft/cli/options/output.go
  cmd/syft/cli/options/output_test.go
  cmd/syft/cli/options/writer_test.go
  go.mod
  go.sum
  syft/format/cyclonedxjson/encoder.go
  syft/format/cyclonedxjson/encoder_test.go
  syft/format/cyclonedxxml/encoder.go
  syft/format/cyclonedxxml/encoder_test.go
  syft/format/internal/cyclonedxutil/encoder.go
  syft/format/internal/testutil/snapshot.go
  syft/format/spdxjson/encoder.go
  syft/format/spdxjson/encoder_test.go
  syft/format/syftjson/encoder.go
  syft/format/syftjson/encoder_test.go
  test/cli/all_formats_expressible_test.go
  test/cli/packages_cmd_test.go
  test/cli/power_user_cmd_test.go
  test/cli/trait_assertions_test.go
  test/integration/encode_decode_cycle_test.go
Labels: enhancement

#2306 Remove the power-user command and related catalogers
  DEVELOPING.md
  README.md
  cmd/syft/cli/cli.go
  cmd/syft/cli/commands/packages.go
  cmd/syft/cli/commands/poweruser.go
  cmd/syft/cli/eventloop/tasks.go
  cmd/syft/cli/options/catalog.go
  cmd/syft/cli/options/file_classification.go
  cmd/syft/cli/options/secrets.go
  cmd/syft/cli/ui/handle_secrets_cataloger.go
  cmd/syft/cli/ui/handle_secrets_cataloger_test.go
  cmd/syft/cli/ui/handler.go
  internal/constants.go
  schema/json/README.md
  schema/json/schema-13.0.0.json
  syft/event/event.go
  syft/event/parsers/parsers.go
  syft/file/cataloger/filecontent/cataloger.go
  syft/file/cataloger/secrets/cataloger.go
  syft/file/cataloger/secrets/cataloger_test.go
  syft/file/cataloger/secrets/generate_search_patterns.go
  syft/file/cataloger/secrets/generate_search_patterns_test.go
  syft/file/cataloger/secrets/newline_counter.go
  syft/file/cataloger/secrets/newline_counter_test.go
  syft/file/cataloger/secrets/secrets_search_by_line_strategy.go
  syft/file/cataloger/secrets/test-fixtures/secrets/default/api-key.txt
  syft/file/cataloger/secrets/test-fixtures/secrets/default/aws.env
  syft/file/cataloger/secrets/test-fixtures/secrets/default/aws.ini
  syft/file/cataloger/secrets/test-fixtures/secrets/default/docker-config.json
  syft/file/cataloger/secrets/test-fixtures/secrets/default/not-docker-config.json
  syft/file/cataloger/secrets/test-fixtures/secrets/default/private-key-false-positive.pem
  syft/file/cataloger/secrets/test-fixtures/secrets/default/private-key-openssl.pem
  syft/file/cataloger/secrets/test-fixtures/secrets/default/private-key.pem
  syft/file/cataloger/secrets/test-fixtures/secrets/default/private-keys.pem
  syft/file/cataloger/secrets/test-fixtures/secrets/multiple.txt
  syft/file/cataloger/secrets/test-fixtures/secrets/simple.txt
  syft/format/syftjson/model/document.go
  syft/format/syftjson/to_format_model.go
  syft/sbom/sbom.go
  test/cli/json_schema_test.go
  test/cli/power_user_cmd_test.go
Labels: breaking-change, json-schema

#2342 fix: add manual namespace mapping for org.bouncycastle jars
  syft/pkg/cataloger/common/cpe/java_groupid_map.go
Labels: bug

#2343 fix: add manual namespace mapping for org.springframework.security jars
  syft/pkg/cataloger/common/cpe/java_groupid_map.go
Labels: bug

#2329 Enhance redis binary classifier to support additional versions
  syft/pkg/cataloger/binary/cataloger_test.go
  syft/pkg/cataloger/binary/default_classifiers.go
  syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/redis-server-7.0.14/redis-server
  syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/redis-server-7.2.3-amd64/redis-server
  syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/redis-server-7.2.3-arm64/redis-server
Labels: enhancement

#2345 fix: add manual namespace mapping for org.springframework jars
  syft/pkg/cataloger/common/cpe/java_groupid_map.go
  test/integration/java_purl_test.go
Labels: bug

#2341 Use read lock in `pkg.Collection`
  syft/pkg/collection.go
  syft/pkg/collection_test.go
Labels: bug

#2371 Use distinct PR label for json schema breaking changes
  .chronicle.yaml
  .github/scripts/labeler.py
  .github/workflows/detect-schema-changes.yaml
Labels: bug, changelog-ignore

#2370 Fix file metadata cataloger when passed explicit coordinates
  syft/file/cataloger/filemetadata/cataloger.go
  syft/file/cataloger/filemetadata/cataloger_test.go
Labels: bug

#2374 Fix tests failing due to Mac Rosetta cache
  syft/internal/fileresolver/container_image_all_layers_test.go
  syft/internal/fileresolver/container_image_squash_test.go
Labels: changelog-ignore
