Repository anchore/syft, pull requests merged in 2024-04, with the labels that each got.

#2791 chore: remove useless code
  syft/pkg/license.go
  syft/source/stereoscopesource/image_source_provider.go
Labels: changelog-ignore

#2801 fix: improvements to known CPE index construction
  syft/pkg/cataloger/internal/cpegenerate/dictionary/data/cpe-index.json
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/nvd.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/expected-cpe-index.json
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/official-cpe-dictionary_v2.3.xml
Labels: bug

#2804 feat: index known CPEs for PHP Composer packagist.org packages
  syft/pkg/cataloger/internal/cpegenerate/dictionary/data/cpe-index.json
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate_test.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/expected-cpe-index.json
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/official-cpe-dictionary_v2.3.xml
  syft/pkg/cataloger/internal/cpegenerate/dictionary/types.go
  syft/pkg/cataloger/internal/cpegenerate/generate.go
Labels: enhancement

#2806 fix: prefer non-deprecated CPEs and include jenkins plugins from plugins.jenkins.io
  syft/pkg/cataloger/internal/cpegenerate/dictionary/data/cpe-index.json
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate_test.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/nvd.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/expected-cpe-index.json
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/official-cpe-dictionary_v2.3.xml
Labels: bug

#2816 feat: index known CPEs for go modules
  syft/pkg/cataloger/internal/cpegenerate/dictionary/data/cpe-index.json
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate_test.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/expected-cpe-index.json
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/official-cpe-dictionary_v2.3.xml
  syft/pkg/cataloger/internal/cpegenerate/dictionary/types.go
  syft/pkg/cataloger/internal/cpegenerate/generate.go
Labels: enhancement
