Repository anchore/syft, pull requests merged in 2024-05, with the labels that each got.

#2844 Restore version file update on release
  .github/scripts/update-version-file.sh
  .github/workflows/release-version-file.yaml
  .github/workflows/release.yaml
  Taskfile.yaml
Labels: bug, changelog-ignore, release

#2846 Remove homebrew core publisher workflow
  .github/workflows/release-homebrew.yaml
Labels: changelog-ignore, release

#2858 README.md: link to official wiki
  README.md
Labels: changelog-ignore

#2862 Fix redundant package deletions when considering ELF packages
  cmd/syft/internal/test/integration/package_binary_elf_relationships_test.go
  internal/relationship/binary/binary_dependencies.go
  internal/relationship/binary/binary_dependencies_test.go
  internal/relationship/binary/shared_library_index_test.go
Labels: bug

#2868 chore: fix small tooling error for go.mod
  syft/pkg/cataloger/golang/test-fixtures/glob-paths/src/go.mod
Labels: changelog-ignore

#2871 Use values in relationship To/From fields
  internal/cmptest/common_options.go
  internal/cmptest/diff_reporter.go
  internal/cmptest/license.go
  internal/cmptest/location.go
  internal/cmptest/relationship.go
  internal/relationship/by_file_ownership.go
  internal/relationship/by_file_ownership_test.go
  syft/pkg/cataloger/internal/pkgtest/test_generic_parser.go
  test/rules/rules.go
Labels: bug

#2865 Fix outdated links to SPDX
  syft/format/internal/spdxutil/helpers/external_ref.go
  syft/format/internal/spdxutil/helpers/license.go
  syft/format/internal/spdxutil/helpers/relationship_type.go
Labels: documentation

#2891 Go Mod Cataloger: Remove Replaced Packages
  syft/pkg/cataloger/golang/parse_go_mod.go
  syft/pkg/cataloger/golang/parse_go_mod_test.go
  syft/pkg/cataloger/golang/test-fixtures/many-packages
Labels: bug

#2864 Added functionality to convert major, minor, patch to version
  syft/pkg/cataloger/binary/classifier.go
  syft/pkg/cataloger/binary/classifier_cataloger.go
  syft/pkg/cataloger/binary/classifier_test.go
  syft/pkg/cataloger/binary/test-fixtures/version-parts.txt
Labels: enhancement

#2893 Handle GOEXPERIMENTs in go version
  internal/constants.go
  schema/json/README.md
  schema/json/schema-16.0.12.json
  schema/json/schema-latest.json
  syft/pkg/cataloger/golang/package.go
  syft/pkg/cataloger/golang/parse_go_binary.go
  syft/pkg/cataloger/golang/parse_go_binary_test.go
  syft/pkg/golang.go
Labels: json-schema
