Repository anchore/syft, pull requests merged in 2024-02, with the labels that each got.

#2553 Translate maps to sequences in package metadata
  internal/constants.go
  schema/json/schema-15.0.0.json
  syft/internal/packagemetadata/discover_type_names.go
  syft/pkg/cataloger/cpp/parse_conanlock.go
  syft/pkg/cataloger/cpp/parse_conanlock_test.go
  syft/pkg/cataloger/golang/package.go
  syft/pkg/cataloger/golang/parse_go_binary.go
  syft/pkg/cataloger/golang/parse_go_binary_test.go
  syft/pkg/cataloger/internal/cpegenerate/generate_test.go
  syft/pkg/cataloger/internal/cpegenerate/java.go
  syft/pkg/cataloger/internal/cpegenerate/java_test.go
  syft/pkg/cataloger/java/archive_parser_test.go
  syft/pkg/cataloger/java/package_url_test.go
  syft/pkg/cataloger/java/parse_java_manifest.go
  syft/pkg/cataloger/java/parse_java_manifest_test.go
  syft/pkg/conan.go
  syft/pkg/golang.go
  syft/pkg/java.go
  syft/pkg/key_value.go
Labels: json-schema, detected-breaking-change

#2581 Restore io.Reader in format API
  syft/format/decoders.go
  syft/pkg/cataloger/java/parse_java_manifest_test.go
Labels: changelog-ignore

#2517 Add API examples
  examples/README.md
  examples/create_custom_sbom/alpine_configuration_cataloger.go
  examples/create_custom_sbom/main.go
  examples/create_simple_sbom/main.go
  examples/decode_sbom/alpine.syft.json
  examples/decode_sbom/main.go
  examples/source_detection/main.go
  examples/source_from_image/main.go
  syft/cataloging/filecataloging/config.go
  syft/create_sbom_config_test.go
Labels: documentation

#2443 Detect ELF security features
  .github/workflows/validations.yaml
  Taskfile.yaml
  cmd/syft/internal/options/catalog.go
  cmd/syft/internal/options/file.go
  internal/constants.go
  internal/task/file_tasks.go
  schema/json/schema-16.0.1.json
  syft/cataloging/filecataloging/config.go
  syft/create_sbom_config.go
  syft/create_sbom_config_test.go
  syft/file/cataloger/executable/cataloger.go
  syft/file/cataloger/executable/elf.go
  syft/file/cataloger/executable/elf_test.go
  syft/file/cataloger/executable/test-fixtures/.gitignore
  syft/file/cataloger/executable/test-fixtures/Dockerfile
  syft/file/cataloger/executable/test-fixtures/Makefile
  syft/file/cataloger/executable/test-fixtures/differ/__main__.py
  syft/file/cataloger/executable/test-fixtures/expected_verify
  syft/file/cataloger/executable/test-fixtures/project/Makefile
  syft/file/cataloger/executable/test-fixtures/project/lib.c
  syft/file/cataloger/executable/test-fixtures/project/lib.h
  syft/file/cataloger/executable/test-fixtures/project/main.c
  syft/file/executable.go
  syft/format/syftjson/decoder_test.go
  syft/format/syftjson/model/file.go
  syft/format/syftjson/to_format_model.go
  syft/format/syftjson/to_syft_model.go
  syft/format/syftjson/to_syft_model_test.go
  syft/internal/unionreader/union_reader.go
  syft/internal/unionreader/union_reader_test.go
  syft/pkg/cataloger/binary/classifier.go
  syft/pkg/cataloger/golang/parse_go_binary.go
  syft/pkg/cataloger/golang/scan_binary.go
  syft/pkg/cataloger/java/graalvm_native_image_cataloger.go
  syft/pkg/cataloger/java/graalvm_native_image_cataloger_test.go
  syft/pkg/cataloger/kernel/parse_linux_kernel_file.go
  syft/pkg/cataloger/kernel/parse_linux_kernel_module_file.go
  syft/pkg/cataloger/rust/parse_audit_binary.go
  syft/sbom/sbom.go
Labels: json-schema

#2403 Add Erlang OTP Application cataloger
  cmd/syft/internal/test/integration/catalog_packages_cases_test.go
  cmd/syft/internal/test/integration/catalog_packages_test.go
  cmd/syft/internal/test/integration/test-fixtures/image-pkg-coverage/pkgs/erlang/accept.app
  go.mod
  go.sum
  internal/task/package_tasks.go
  syft/format/internal/spdxutil/helpers/source_info.go
  syft/format/internal/spdxutil/helpers/source_info_test.go
  syft/pkg/cataloger/erlang/cataloger.go
  syft/pkg/cataloger/erlang/cataloger_test.go
  syft/pkg/cataloger/erlang/package.go
  syft/pkg/cataloger/erlang/parse_otp_app.go
  syft/pkg/cataloger/erlang/parse_otp_app_test.go
  syft/pkg/cataloger/erlang/parse_rebar_lock.go
  syft/pkg/cataloger/erlang/test-fixtures/glob-paths/src/rabbitmq.app
  syft/pkg/cataloger/erlang/test-fixtures/rabbitmq.app
  syft/pkg/language.go
  syft/pkg/type.go
  syft/pkg/type_test.go
Labels: enhancement

#2350 Adding metadata fields when parsing yarn.lock and poetry.lock
  internal/constants.go
  schema/json/schema-16.0.2.json
  syft/internal/packagemetadata/generated.go
  syft/internal/packagemetadata/names.go
  syft/pkg/cataloger/javascript/package.go
  syft/pkg/cataloger/javascript/parse_yarn_lock.go
  syft/pkg/cataloger/javascript/parse_yarn_lock_test.go
  syft/pkg/cataloger/python/package.go
  syft/pkg/cataloger/python/parse_pipfile_lock.go
  syft/pkg/cataloger/python/parse_poetry_lock.go
  syft/pkg/cataloger/python/parse_poetry_lock_test.go
  syft/pkg/cataloger/python/test-fixtures/poetry/poetry.lock
  syft/pkg/npm.go
  syft/pkg/python.go
Labels: enhancement, json-schema

#2588 Labeler should ignore latest version
  .github/scripts/labeler.py
  .github/scripts/labeler_test.py
Labels: changelog-ignore

#2612 Fix readme example around templating behavior
  README.md
Labels: documentation

#2642 Test for field conventions in json schema
  syft/format/syftjson/schema_test.go
Labels: changelog-ignore

#2643 Rename binary classifier cataloger name
  syft/pkg/cataloger/binary/cataloger.go
Labels: changelog-ignore

#2663 chore: update busybox image for acceptance tests
  test/install/Makefile
Labels: changelog-ignore

#2635 Enforce breaking change bump major version
  .chronicle.yaml
Labels: changelog-ignore
