Repository anchore/syft, pull requests merged in 2024-10, with the labels that each got.

#3306 [chore] Add mastodon link to README.md
  README.md
Labels: changelog-ignore

#3310 docs: clearer deprecation message for --file
  cmd/syft/internal/options/output_file.go
Labels: documentation

#3318 Update the release docs
  RELEASE.md
Labels: documentation, release

#3330 fix: stop some log.Warn spam due parsing an empty string as a CPE
  syft/pkg/cataloger/binary/elf_package.go
Labels: bug

#3339 fix: improve mariadb binary classifer to detect older versions
  syft/pkg/cataloger/binary/classifiers.go
Labels: bug

#3348 Create single license scanner for all catalogers
  internal/licenses/context.go
  internal/licenses/parser.go
  internal/licenses/scanner.go
  internal/licenses/search.go
  syft/create_sbom.go
  syft/pkg/cataloger/generic/cataloger.go
  syft/pkg/cataloger/golang/licenses.go
  syft/pkg/cataloger/golang/licenses_test.go
  syft/pkg/cataloger/golang/package.go
  syft/pkg/cataloger/golang/parse_go_binary.go
  syft/pkg/cataloger/golang/parse_go_binary_test.go
  syft/pkg/cataloger/golang/parse_go_mod.go
  syft/pkg/cataloger/java/archive_parser.go
  syft/pkg/cataloger/java/archive_parser_test.go
  syft/pkg/cataloger/python/package.go
  syft/pkg/cataloger/python/parse_wheel_egg.go
Labels: bug, performance

#3391 fix: malformed pom.xml may cause recursive loop
  syft/pkg/cataloger/java/internal/maven/resolver.go
  syft/pkg/cataloger/java/internal/maven/resolver_test.go
  syft/pkg/cataloger/java/internal/maven/test-fixtures/local/circular-1/pom.xml
  syft/pkg/cataloger/java/internal/maven/test-fixtures/local/circular-2/pom.xml
  syft/pkg/cataloger/java/internal/maven/test-fixtures/maven-repo/my/org/circular/1.2.3/circular-1.2.3.pom
Labels: bug
