Repository anchore/syft, pull requests merged in 2024-12, with the labels that each got.

#3498 chore: add and document target for updating unit snapshots
  DEVELOPING.md
  Taskfile.yaml
Labels: changelog-ignore

#3502 fix order of rust dependencies and support git sources in Cargo.lock dependencies
  syft/pkg/cataloger/rust/parse_cargo_lock.go
  syft/pkg/cataloger/rust/parse_cargo_lock_test.go
  syft/pkg/cataloger/rust/test-fixtures/Cargo.lock-with-git-deps
Labels: bug

#3500 Add relationships for rust audit binary packages
  cmd/syft/internal/options/source.go
  syft/internal/fileresolver/file_indexer.go
  syft/internal/fileresolver/file_indexer_test.go
  syft/internal/fileresolver/filetree_resolver_test.go
  syft/pkg/cataloger/rust/cataloger.go
  syft/pkg/cataloger/rust/cataloger_test.go
  syft/pkg/cataloger/rust/package.go
  syft/pkg/cataloger/rust/parse_audit_binary.go
  syft/pkg/cataloger/rust/test-fixtures/image-audit/Cargo.lock
  syft/pkg/cataloger/rust/test-fixtures/image-audit/Cargo.toml
  syft/pkg/cataloger/rust/test-fixtures/image-audit/Dockerfile
  syft/pkg/cataloger/rust/test-fixtures/image-audit/src/main.rs
Labels: enhancement

#3510 chore(deps): update anchore dependencies
  go.mod
  go.sum
Labels: dependencies, pre-release
