Repository anchore/syft, pull requests merged in 2024-06, with the labels that each got.

#2922 Close sqlite driver after testing sqlite availability
  syft/pkg/cataloger/redhat/cataloger.go
Labels: bug

#2926 Use tool for DCO checks
  .github/workflows/dco.yaml
Labels: changelog-ignore

#2924 Remove unused test fixtures and empty directories
  test/cli/test-fixtures/image-secrets-dir/Dockerfile
  test/cli/test-fixtures/image-secrets-dir/api-key.txt
  test/cli/test-fixtures/image-secrets/Dockerfile
  test/cli/test-fixtures/image-secrets/api-key.txt
Labels: changelog-ignore

#2890 feat: add license field to ELF binary package metadata
  syft/pkg/cataloger/binary/elf_package.go
  syft/pkg/cataloger/binary/elf_package_cataloger.go
  syft/pkg/cataloger/binary/elf_package_cataloger_test.go
  syft/pkg/cataloger/binary/elf_package_test.go
Labels: enhancement

#2944 Pin golang image version in test fixture
  syft/pkg/cataloger/golang/test-fixtures/image-not-a-module/Dockerfile
Labels: changelog-ignore

#2945 Trim whitespace from wordpress values
  syft/pkg/cataloger/wordpress/parse_plugin.go
  syft/pkg/cataloger/wordpress/parse_plugin_test.go
Labels: bug

#2946 Consider `Author` field for wordpress plugins when generating CPEs
  syft/pkg/cataloger/internal/cpegenerate/generate.go
  syft/pkg/cataloger/internal/cpegenerate/generate_test.go
  syft/pkg/cataloger/internal/cpegenerate/wordpress.go
  syft/pkg/cataloger/internal/cpegenerate/wordpress_test.go
Labels: enhancement, ecosystem:php

#2976 chore: enable dependabot to keep boostrap action updated
  .github/actions/bootstrap/action.yaml
  .github/dependabot.yml
Labels: changelog-ignore

#2983 docs: update cyclone-dx documentation
  README.md
Labels: changelog-ignore
