Repository anchore/syft, pull requests merged in 2024-11, with the labels that each got.

#3410 chore: update executor back to default of not bubbling errors to main flow
  internal/task/executor.go
  internal/unknown/path_error.go
  internal/unknown/path_error_test.go
  syft/pkg/cataloger/binary/classifier_cataloger.go
  syft/pkg/cataloger/binary/classifier_cataloger_test.go
  test/cli/test-fixtures/image-unknowns/Dockerfile
  test/cli/unknowns_test.go
Labels: bug

#3417 chore: build release sbom from go.mod
  .github/workflows/release.yaml
Labels: changelog-ignore, release

#3443 feat: emit dependency relationships found in Cargo.lock
  syft/pkg/cataloger/rust/parse_cargo_lock.go
  syft/pkg/cataloger/rust/parse_cargo_lock_test.go
  syft/pkg/cataloger/rust/test-fixtures/Cargo.lock
Labels: enhancement
