Repository anchore/syft, pull requests merged in 2024-09, with the labels that each got.

#3218 chore: restore ci-check.sh script
  .github/scripts/ci-check.sh
  Taskfile.yaml
Labels: changelog-ignore

#3250 fix: capture-snippet.sh can handle leading whitespaces now (#3249)
  syft/pkg/cataloger/binary/test-fixtures/capture-snippet.sh
Labels: changelog-ignore

#3252 feat: add binary classifiers for lighttp, proftpd, zstd, xz, gzip, jq, and sqlcipher
  syft/pkg/cataloger/binary/classifier_cataloger_test.go
  syft/pkg/cataloger/binary/classifiers.go
  syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/gzip/1.12/linux-amd64/gzip
  syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/jq/1.7.1/linux-amd64/jq
  syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/lighttpd/1.4.76/linux-amd64/lighttpd
  syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/proftpd/1.3.8b/linux-amd64/proftpd
  syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/sqlcipher/4.5.5/linux-amd64/sqlcipher
  syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/xz/5.6.2/linux-amd64/xz
  syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/zstd/1.5.6/linux-amd64/zstd
  syft/pkg/cataloger/binary/test-fixtures/config.yaml
Labels: enhancement

#3257 Add compliance policy for empty name and version
  cmd/syft/internal/options/catalog.go
  cmd/syft/internal/options/compliance.go
  internal/relationship/index.go
  internal/relationship/index_test.go
  internal/task/package_task_factory.go
  internal/task/package_task_factory_test.go
  syft/cataloging/compliance.go
  syft/create_sbom_config.go
  syft/pkg/cataloger/ocaml/parse_opam_test.go
Labels: enhancement

#3269 Improve subpath to mount matching
  syft/internal/fileresolver/path_skipper.go
  syft/internal/fileresolver/path_skipper_test.go
Labels: bug

#3272 Add awaiting response management
  .github/workflows/remove-awaiting-response-label.yaml
Labels: changelog-ignore
