Repository anchore/syft, pull requests merged in 2024-01, with the labels that each got.

#2499 Condense binary cataloger config in JSON output
  syft/pkg/cataloger/binary/cataloger.go
  syft/pkg/cataloger/binary/cataloger_test.go
  syft/pkg/cataloger/binary/classifier.go
  syft/pkg/cataloger/binary/classifier_test.go
Labels: bug

#2366 Add cataloger list command
  cmd/syft/cli/cli.go
  cmd/syft/cli/commands/attest.go
  cmd/syft/cli/commands/cataloger.go
  cmd/syft/cli/commands/cataloger_list.go
  cmd/syft/cli/commands/cataloger_list_test.go
  cmd/syft/cli/commands/packages.go
  go.mod
  go.sum
Labels: enhancement

#2504 Include binary cataloger configuration defaults
  syft/cataloging/pkgcataloging/config.go
Labels: bug

#2516 fix: remove second call to finalize as the task handles it
  syft/create_sbom.go
  test/integration/regression_sbom_duplicate_relationships_test.go
Labels: bug

#2520 Update readme and help output to be accurate to the Syft API
  README.md
  cmd/syft/cli/commands/scan.go
  cmd/syft/cli/commands/scan_test.go
Labels: documentation

#2522 Deduplicate digests from user configuration
  cmd/syft/cli/options/file.go
  cmd/syft/cli/options/file_test.go
  cmd/syft/cli/options/source.go
  cmd/syft/cli/options/source_test.go
  internal/file/digest.go
  internal/file/normalize_hashes.go
  internal/file/normalize_hashes_test.go
  syft/cataloging/filecataloging/config.go
  syft/file/cataloger/filedigest/cataloger.go
Labels: bug

#2518 make AllLocations accept a context
  go.mod
  go.sum
  syft/file/cataloger/filemetadata/cataloger.go
  syft/file/cataloger/internal/all_regular_files.go
  syft/file/mock_resolver.go
  syft/file/resolver.go
  syft/internal/fileresolver/container_image_all_layers.go
  syft/internal/fileresolver/container_image_all_layers_test.go
  syft/internal/fileresolver/container_image_squash.go
  syft/internal/fileresolver/container_image_squash_test.go
  syft/internal/fileresolver/deferred.go
  syft/internal/fileresolver/directory.go
  syft/internal/fileresolver/directory_test.go
  syft/internal/fileresolver/empty.go
  syft/internal/fileresolver/excluding_file.go
  syft/internal/fileresolver/excluding_file_test.go
  syft/internal/fileresolver/unindexed_directory.go
  syft/internal/fileresolver/unindexed_directory_test.go
  syft/pkg/cataloger/binary/cataloger_test.go
  syft/pkg/cataloger/internal/pkgtest/observing_resolver.go
  syft/pkg/cataloger/nix/cataloger.go
  syft/pkg/cataloger/redhat/parse_rpm_db_test.go
Labels: breaking-change

#2515 Swap format uses of io.ReadSeeker for io.Reader
  syft/format/cyclonedxjson/decoder.go
  syft/format/cyclonedxxml/decoder.go
  syft/format/decoders.go
  syft/format/internal/cyclonedxutil/decoder.go
  syft/format/internal/stream/seekable_reader.go
  syft/format/internal/stream/seekable_reader_test.go
  syft/format/spdxjson/decoder.go
  syft/format/spdxtagvalue/decoder.go
  syft/format/syftjson/decoder.go
  syft/sbom/format.go
Labels: enhancement

#2534 chore: stop re-exporting wfn.Attributes
  syft/cpe/by_specificity.go
  syft/cpe/cpe.go
  syft/cpe/cpe_test.go
  syft/format/common/cyclonedxhelpers/cpe.go
  syft/format/common/cyclonedxhelpers/format.go
  syft/format/common/spdxhelpers/external_refs.go
  syft/format/common/spdxhelpers/external_refs_test.go
  syft/format/syftjson/to_format_model.go
  syft/pkg/cataloger/binary/classifier_test.go
  syft/pkg/cataloger/common/cpe/filter.go
  syft/pkg/cataloger/common/cpe/generate.go
  syft/pkg/cataloger/common/cpe/generate_test.go
  syft/pkg/cataloger/golang/cataloger_test.go
Labels: breaking-change

#2540 Allow for RPM modularity to be optional
  internal/constants.go
  schema/json/schema-14.0.0.json
  syft/pkg/cataloger/redhat/parse_rpm_db.go
  syft/pkg/cataloger/redhat/parse_rpm_db_test.go
  syft/pkg/rpm.go
Labels: json-schema, detected-breaking-change

#2530 Unexport types and functions cataloger packages
  syft/cataloging/pkgcataloging/config.go
  syft/pkg/cataloger/binary/cataloger.go
  syft/pkg/cataloger/cpp/parse_conanfile.go
  syft/pkg/cataloger/golang/parse_go_binary.go
  syft/pkg/cataloger/java/cataloger.go
  syft/pkg/cataloger/java/graalvm_native_image_cataloger.go
  syft/pkg/cataloger/java/parse_gradle_lockfile.go
  syft/pkg/cataloger/kernel/cataloger.go
  syft/pkg/cataloger/nix/cataloger.go
  syft/pkg/cataloger/python/cataloger.go
  syft/pkg/cataloger/python/parse_pipfile_lock.go
  test/integration/package_cataloger_convention_test.go
Labels: breaking-change

#2542 Use the json schema as input for templating
  README.md
  cmd/syft/internal/options/format_template.go
  syft/format/encoders.go
  syft/format/template/encoder.go
  syft/format/template/encoder_test.go
  syft/format/template/test-fixtures/csv-hasField.template
  syft/format/template/test-fixtures/csv.template
  syft/format/template/test-fixtures/legacy/csv-hasField.template
  syft/format/template/test-fixtures/legacy/csv.template
  syft/format/template/test-fixtures/snapshot/TestFormatWithOptionAndHasField_Legacy.golden
  syft/format/template/test-fixtures/snapshot/TestFormatWithOption_Legacy.golden
  test/cli/test-fixtures/csv.template
Labels: breaking-change

#2547 Implement golang Purl subpath
  syft/pkg/cataloger/golang/package.go
  syft/pkg/cataloger/golang/package_test.go
  syft/pkg/cataloger/golang/parse_go_binary_test.go
Labels: bug

#2541 Internalize CPE generation logic
  syft/cpe/cpe.go
  syft/pkg/cataloger/common/cpe/create.go
  syft/pkg/cataloger/internal/cpegenerate/apk.go
  syft/pkg/cataloger/internal/cpegenerate/apk_test.go
  syft/pkg/cataloger/internal/cpegenerate/candidate_by_package_type.go
  syft/pkg/cataloger/internal/cpegenerate/candidate_by_package_type_test.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/data/cpe-index.json
  syft/pkg/cataloger/internal/cpegenerate/dictionary/generate_index.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate_test.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/main.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/nvd.go
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/expected-cpe-index.json
  syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/official-cpe-dictionary_v2.3.xml
  syft/pkg/cataloger/internal/cpegenerate/dictionary/types.go
  syft/pkg/cataloger/internal/cpegenerate/field_candidate.go
  syft/pkg/cataloger/internal/cpegenerate/field_candidate_filter.go
  syft/pkg/cataloger/internal/cpegenerate/field_candidate_test.go
  syft/pkg/cataloger/internal/cpegenerate/filter.go
  syft/pkg/cataloger/internal/cpegenerate/filter_test.go
  syft/pkg/cataloger/internal/cpegenerate/generate.go
  syft/pkg/cataloger/internal/cpegenerate/generate_test.go
  syft/pkg/cataloger/internal/cpegenerate/go.go
  syft/pkg/cataloger/internal/cpegenerate/go_test.go
  syft/pkg/cataloger/internal/cpegenerate/java.go
  syft/pkg/cataloger/internal/cpegenerate/java_groupid_map.go
  syft/pkg/cataloger/internal/cpegenerate/java_test.go
  syft/pkg/cataloger/internal/cpegenerate/javascript.go
  syft/pkg/cataloger/internal/cpegenerate/python.go
  syft/pkg/cataloger/internal/cpegenerate/rpm.go
  syft/pkg/cataloger/internal/cpegenerate/ruby.go
  syft/pkg/cataloger/internal/cpegenerate/utils.go
  syft/pkg/cataloger/internal/cpegenerate/utils_test.go
  syft/pkg/cataloger/internal/cpegenerate/vendors_from_url.go
  syft/pkg/cataloger/internal/cpegenerate/vendors_from_url_test.go
  syft/pkg/cataloger/java/package_url.go
Labels: breaking-change

#2548 Sign checksums file and add SBOMs on release
  .binny.yaml
  .goreleaser.yaml
  test/install/1_download_snapshot_asset_test.sh
  test/install/environments/Dockerfile-alpine-3.6
  test/install/environments/Dockerfile-ubuntu-20.04
Labels: release

#2570 Bump archiver and stereoscope to address path traversal issues
  go.mod
  go.sum
Labels: security

#2571 Revert cosign signing of release checksums file
  .goreleaser.yaml
Labels: bug, release

#2572 Re-add cosign signing checksums file
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: changelog-ignore, release

#2564 chore: pluralize the flag
  README.md
Labels: changelog-ignore

#2573 fix(java): improve identification for org.apache.kafka artifacts
  cmd/syft/internal/test/integration/java_purl_test.go
  syft/pkg/cataloger/internal/cpegenerate/java_groupid_map.go
Labels: bug
