Repository anchore/syft, pull requests merged in 2025-04, with the labels that each got.

#3773 Unpin go version in CI
  .github/actions/bootstrap/action.yaml
Labels: changelog-ignore

#3791 Empty source during decoding an SBOM document should not be fatal
  syft/format/syftjson/model/source.go
  syft/format/syftjson/model/source_test.go
Labels: bug

#3812 fix:Use module name over relative paths in `go.mod` replace directives
  syft/pkg/cataloger/golang/parse_go_mod.go
  syft/pkg/cataloger/golang/parse_go_mod_test.go
  syft/pkg/cataloger/golang/test-fixtures/relative-replace
Labels: bug

#3821 PE cataloger should consider compile target paths from deps.json
  syft/pkg/cataloger/dotnet/cataloger_test.go
  syft/pkg/cataloger/dotnet/deps_binary_cataloger.go
  syft/pkg/cataloger/dotnet/deps_json.go
  syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/.gitignore
  syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/Dockerfile
  syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/src/Program.cs
  syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/src/helloworld.csproj
Labels: bug

#3822 Consider DLL claims for dependencies of .NET packages from deps.json
  cmd/syft/internal/options/catalog.go
  cmd/syft/internal/options/dotnet.go
  internal/licenses/context_test.go
  syft/pkg/cataloger/dotnet/cataloger_test.go
  syft/pkg/cataloger/dotnet/config.go
  syft/pkg/cataloger/dotnet/deps_binary_cataloger.go
  syft/pkg/cataloger/dotnet/deps_json.go
  syft/pkg/cataloger/dotnet/package.go
  syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/Dockerfile
  syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/src/Program.cs
  syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/src/helloworld.csproj
Labels: bug

#3825 Add support for detecting javascript assets in .NET projects using libman
  syft/pkg/cataloger/dotnet/cataloger_test.go
  syft/pkg/cataloger/dotnet/deps_binary_cataloger.go
  syft/pkg/cataloger/dotnet/deps_json.go
  syft/pkg/cataloger/dotnet/libman_json.go
  syft/pkg/cataloger/dotnet/test-fixtures/image-net6-asp-libman/.dockerignore
  syft/pkg/cataloger/dotnet/test-fixtures/image-net6-asp-libman/.gitignore
  syft/pkg/cataloger/dotnet/test-fixtures/image-net6-asp-libman/Dockerfile
  syft/pkg/cataloger/dotnet/test-fixtures/image-net6-asp-libman/src/.gitignore
  syft/pkg/cataloger/dotnet/test-fixtures/image-net6-asp-libman/src/LibManSample.csproj
  syft/pkg/cataloger/dotnet/test-fixtures/image-net6-asp-libman/src/Program.cs
  syft/pkg/cataloger/dotnet/test-fixtures/image-net6-asp-libman/src/Startup.cs
  syft/pkg/cataloger/dotnet/test-fixtures/image-net6-asp-libman/src/libman.json
  syft/pkg/cataloger/dotnet/test-fixtures/image-net6-asp-libman/src/vendor/lodash.js
  syft/pkg/cataloger/dotnet/test-fixtures/image-net6-asp-libman/src/vendor/lodash.min.js
Labels: enhancement
