Repository anchore/syft, pull requests merged in 2025-03, with the labels that each got.

#3647 Support extracting symbols in .dynsym section for GraalVM Native Images
  syft/pkg/cataloger/java/graalvm_native_image_cataloger.go
Labels: enhancement

#3720 Location order on packages should consider evidence annotations when sorting
  internal/cmptest/common_options.go
  internal/cmptest/license.go
  internal/cmptest/location.go
  internal/cmptest/set.go
  internal/evidence/constants.go
  internal/relationship/by_file_ownership_test.go
  syft/file/location_set_test.go
  syft/file/locations.go
  syft/pkg/cataloger/debian/cataloger_test.go
  syft/pkg/cataloger/golang/stdlib_package_test.go
  syft/pkg/cataloger/internal/pkgtest/test_generic_parser.go
  syft/pkg/cataloger/python/parse_wheel_egg_metadata_test.go
  syft/pkg/evidence.go
Labels: bug

#3754 chore: reformat imports
  cmd/syft/internal/options/cache.go
  cmd/syft/internal/options/cache_test.go
  cmd/syft/internal/options/output_file.go
  cmd/syft/internal/options/writer.go
  cmd/syft/internal/options/writer_test.go
  syft/format/template/encoder.go
  syft/internal/fileresolver/unindexed_directory.go
  syft/pkg/cataloger/golang/config.go
  syft/pkg/cataloger/golang/config_test.go
  syft/pkg/cataloger/java/internal/maven/config.go
  syft/pkg/cataloger/java/internal/maven/config_test.go
  syft/source/directorysource/directory_source_provider.go
  syft/source/filesource/file_source_provider.go
Labels: changelog-ignore

#3764 Improve .NET package CPE generation
  syft/pkg/cataloger/dotnet/cataloger_test.go
  syft/pkg/cataloger/dotnet/package_test.go
  syft/pkg/cataloger/internal/cpegenerate/dotnet.go
  syft/pkg/cataloger/internal/cpegenerate/generate.go
  syft/pkg/cataloger/internal/cpegenerate/generate_test.go
  syft/pkg/cataloger/internal/cpegenerate/rpm.go
Labels: enhancement
