Repository anchore/syft, pull requests merged in 2025-05, with the labels that each got.

#3844 Do not use hashes for SPDX license names/expressions
  syft/format/internal/spdxutil/helpers/license.go
  syft/format/internal/spdxutil/helpers/license_test.go
  syft/format/internal/spdxutil/helpers/spdxid.go
Labels: enhancement

#3857 fix: use "contents" field and remove "fullText" license field
  syft/format/internal/spdxutil/helpers/license.go
  syft/format/internal/spdxutil/helpers/license_test.go
  syft/format/spdxjson/test-fixtures/snapshot/TestSPDXJSONDirectoryEncoder.golden
  syft/format/spdxjson/test-fixtures/snapshot/TestSPDXJSONImageEncoder.golden
  syft/format/spdxjson/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
  syft/format/spdxtagvalue/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
  syft/format/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueDirectoryEncoder.golden
  syft/format/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueImageEncoder.golden
  syft/format/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
  syft/format/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
  syft/format/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
  syft/format/syftjson/to_format_model.go
  syft/pkg/license.go
  syft/pkg/license_set_test.go
  syft/pkg/license_test.go
Labels: changelog-ignore

#3855 Annotate visible/hidden paths when all-layers scope
  syft/internal/fileresolver/container_image_all_layers.go
  syft/internal/fileresolver/container_image_all_layers_test.go
  syft/internal/fileresolver/container_image_deep_squash.go
Labels: enhancement

#1872 Use package ID from decoded SBOMs when provided
  internal/cmptest/location.go
  syft/format/common/spdxhelpers/to_format_model.go
  syft/format/common/spdxhelpers/to_format_model_test.go
  syft/format/common/spdxhelpers/to_syft_model.go
  syft/format/common/spdxhelpers/to_syft_model_test.go
  syft/format/cyclonedxjson/encoder_test.go
  syft/format/cyclonedxjson/test-fixtures/snapshot/TestCycloneDxDirectoryEncoder.golden
  syft/format/cyclonedxjson/test-fixtures/snapshot/TestCycloneDxImageEncoder.golden
  syft/format/cyclonedxxml/encoder_test.go
  syft/format/cyclonedxxml/test-fixtures/snapshot/TestCycloneDxDirectoryEncoder.golden
  syft/format/cyclonedxxml/test-fixtures/snapshot/TestCycloneDxImageEncoder.golden
  syft/format/internal/cyclonedxutil/helpers/decoder.go
  syft/format/internal/cyclonedxutil/helpers/decoder_test.go
  syft/format/internal/testutil/redactor.go
  syft/format/syftjson/to_syft_model.go
  syft/internal/fileresolver/container_image_squash_test.go
  syft/pkg/package.go
Labels: enhancement

#3869 Merge multiple targets for the same .NET package
  syft/pkg/cataloger/dotnet/deps_binary_cataloger.go
  syft/pkg/cataloger/dotnet/deps_json.go
  syft/pkg/cataloger/dotnet/deps_json_test.go
Labels: bug

#3894 chore: update fixtures based on CI builds
  syft/format/cyclonedxxml/encoder_test.go
  syft/pkg/cataloger/python/cataloger_test.go
  syft/pkg/cataloger/python/test-fixtures/image-multi-site-package/Dockerfile
Labels: changelog-ignore

#3901 chore: delete unused cli license fixture
  test/cli/test-fixtures/image-unknown-licenses/Dockerfile
Labels: changelog-ignore

#3896 chore: fix publishing test fixture images
  Taskfile.yaml
  cmd/syft/internal/test/integration/package_deduplication_test.go
Labels: changelog-ignore

#3906 chore: Remove benchmark testing CI workflow
  .github/workflows/benchmark-testing.yaml
  Taskfile.yaml
Labels: changelog-ignore

#3934 fix(terraform): terraform provider lock entries should not require constraints
  syft/pkg/cataloger/terraform/cataloger_test.go
  syft/pkg/cataloger/terraform/test-fixtures/two-providers/.terraform.lock.hcl
  syft/pkg/terraform.go
Labels: bug
